### ISSUE TITLE
Autenticazione git push

### ISSUE THREAD

**Issue by riccardolongo** [HiPeRT/IndInf22#1]
Problema:
Come si fa ad autenticarsi su git utilizzando windows?

**Comment by pburgio** [comment]
Could you plese close the issue and provide the solution?

Thanks

**Comment by riccardolongo** [comment]
Quando si utilizza il comando `git clone`, invece di utilizzare l'indirizzo in https, bisogna utilizzare quello in ssh.
Questo perchè altrimenti ci si imbatte nell'errore 403, che nega l'autorizzazione del nostro `git push`.
Se si è già fatto il clone in https possiamo cambiarlo usando `git remote set-url origin <indirizzo_ssh>`; possiamo visualizzare l'indirizzo corrente selezionato con `git remote -v`.
Ora dobbiamo generare la nostra chiave ssh, per farlo scriviamo sul nostro terminale `ssh-keygen`.
In questo modo abbiamo creato in Linux una cartella ".ssh" contenente due chiavi, quella pubblica e quella privata.
Quella che ci interessa è la chiave pubblica nominata "id_rsa.pub", apriamola e copiamo il testo.
Per autenticarla bisogna andare sul nostro profilo di GitHub, accedere a "SSH and GPG keys" e cliccare sul pulsante verde "New SSH key". Inseriamo un nome, incolliamo il testo della chiave pubblica nel riquadro apposito, selezioniamo "Authentification Keys" ed inviamo. 
Torniamo sul nostro terminale e inseriamo `ssh -vT git@github.com` per confermare l'autentificazione.
Inseriamo poi `git fetch` ed infine `git push --set-upsteam origin <cartella utente>`.
