### ISSUE TITLE
Automata1 in Python

### ISSUE THREAD

**Issue by pburgio** [HiPeRT/IndInf22#3]
@RiccardoNecula  can you please provide a stable implementation?

Thanks

**Comment by RiccardoNecula** [comment]
I've pushed on branch "rickh". I created a new directory for features but i couldn't push my file on features/automata1-in-python because I cannot find it. What i have to do?

**Comment by RiccardoNecula** [comment]
I've resolved the problem by firstly pulling and after merging my branch with the correct branch.
