### ISSUE TITLE
Problemi ad inviare le modifiche di automata-1

### ISSUE THREAD

**Issue by riccardolongo** [HiPeRT/IndInf22#6]
Mi scuso per il disturbo professore Burgio, ma sto avendo problemi ad inviare le modifiche di automata-1.
Ho aperto il mio terminale e per prima cosa ho digitato `cd IndInf22`, subito dopo `git branch -l` per verificare in quale branch ero.
Mi sono spostato dal branch "ricca" al branch "master" con `git checkout master` e ho eliminato il vecchio branch con `git branch --delete ricca`. Successivamente ho modificato il file "automata-1-solution" e ho provato a fare `git push --set-upsteam origin master`, però mi ha dato un messaggio di errore che recita "push di alcuni riferimenti su 'github.com:HiPeRT/IndInf22.git' non riuscito". 
Come suggerimento, mi dice in sostanza che gli aggiornamenti sono stati rifiutati perchè il "remoto" contiene delle modifiche che non ho in locale e mi consiglia di usare `git pull` per integrare le modifiche.
Per cui ho digitato `git pull origin master`, ma mi ha dato "fatal: Need to specify how to reconcile divergent branches.".
Ho eseguito `git fetch` e riprovato `git pull origin master`, ridandomi però lo stesso errore.
Ho provato anche con `git clone git@github.com:HiPeRT/IndInf22.git` e `git merge master`, ma nemmeno così sono riuscito ad eseguire il comando di push.
Mi è venuto il dubbio, e vorrei chiederle, è successo tutto questo perchè ho eliminato prematuramente il mio branch o ho fatto qualcosa d'altro che non andava bene?

**Comment by pburgio** [comment]
Closed on behalf or @riccardolongo
